apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylocation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mylocation
  template:
    metadata:
      labels:
        app: mylocation
    spec:
      containers:
      - name: mylocation
        image: quay.io/donschenck/mylocation:v1
        ports:
        - containerPort: 80
        env:
        - name: LOCATION_SERVICE_URI
          value: "http://locationms.test.svc:8080/"
          